"""
Packs ../png/<name>_64.png and <name>_96.png into RGB565 and writes
sw/bat_source/Core/Src/icon_seed_data.c, replacing its content with the
hand-authored set at both resolutions. Each resolution's arrays are wrapped
in `#if ICON_STORE_ICON_SIZE == ICON_SIZE_64 / ICON_SIZE_96` (see
icon_store.h's compile mask) so only the active size is actually compiled
in; array/variable names match the original file's convention. Does not
touch icon_seed_data.h (unaffected by the size change).

Requires: Pillow.
Usage: python3 export_firmware.py
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
PNG_DIR = os.path.join(ROOT, 'png')
FIRMWARE_C = os.path.join(HERE, '..', '..', '..', '..', 'sw', 'bat_source',
                          'Core', 'Src', 'icon_seed_data.c')

# (png/svg name, firmware array-name stem) -- the two source icons drop the
# "_source" suffix to match the array names already used in the firmware.
ORDER = [
    ('60v_source', '60v'),
    ('10a_source', '10a'),
    ('milliohmmeter', 'milliohmmeter'),
    ('ohmmeter', 'ohmmeter'),
    ('isolation', 'isolation'),
    ('voltmeter', 'voltmeter'),
    ('ampmeter', 'ampmeter'),
    ('charge', 'charge'),
    ('settings', 'settings'),
]
SIZES = [64, 96]

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def emit_array(name, pixels):
    lines = [f'static const uint16_t {name}_data[{len(pixels)}] = {{']
    for i in range(0, len(pixels), 12):
        row = pixels[i:i+12]
        lines.append('\t' + ', '.join(f'0x{v:04x}' for v in row) + ',')
    lines.append('};')
    return '\n'.join(lines)

def size_block(size):
    arrays = []
    struct_entries = []
    for png_name, array_stem in ORDER:
        im = Image.open(os.path.join(PNG_DIR, f'{png_name}_{size}.png')).convert('RGB')
        assert im.size == (size, size), im.size
        pixels = [rgb565(*im.getpixel((x, y))) for y in range(size) for x in range(size)]
        arrays.append(emit_array(f'icon_{array_stem}', pixels))
        struct_entries.append(f'\t{{ ICON_STORE_ICON_WIDTH, ICON_STORE_ICON_HEIGHT, icon_{array_stem}_data }},')

    guard = f'ICON_SIZE_{size}'
    block = f'#if ICON_STORE_ICON_SIZE == {guard}\n\n'
    block += '\n\n'.join(arrays) + '\n\n'
    block += 'const icon_seed_t icon_seeds[ICON_STORE_ICON_COUNT] = {\n'
    block += '\n'.join(struct_entries) + '\n};\n\n'
    block += '#endif\n'
    return block

def main():
    header = """/*
 * icon_seed_data.c
 *
 * Auto-generated by doc/icons/improved_icons/scripts/export_firmware.py --
 * do not hand-edit. RGB565. See doc/icons/improved_icons/svg for the
 * hand-authored vector sources (analog-gauge meters, schematic source
 * symbols, and pictogram icons for isolation/charge/settings) drawn in the
 * carousel's circular/ring style. Seeded at two resolutions -- see
 * icon_store.h's ICON_STORE_ICON_SIZE compile mask to pick which one
 * actually builds in.
 */

#include "icon_seed_data.h"
#ifdef ICON_INCLUDE_SEED

"""
    c_src = header
    c_src += '\n'.join(size_block(size) for size in SIZES)
    c_src += '#endif /* ICON_INCLUDE_SEED */\n'

    with open(FIRMWARE_C, 'w') as f:
        f.write(c_src)

    print('wrote', FIRMWARE_C, 'with', len(ORDER), 'icons at sizes', SIZES)

if __name__ == '__main__':
    main()
