"""
Packs ../png/<name>_64.png into RGB565 and emits ../icon_seed_data_64.c/.h,
in the same {width, height, pixels} layout as the firmware's
sw/bat_source/Core/Src/icon_seed_data.c (which is 48x48).

Requires: Pillow.
Usage: python3 png2rgb565.py
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
PNG_DIR = os.path.join(ROOT, 'png')

ORDER = ['60v_source', '10a_source', 'milliohmmeter', 'ohmmeter', 'isolation',
         'voltmeter', 'ampmeter', 'charge', 'settings']
SIZE = 64

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def emit_array(name, pixels):
    lines = [f'static const uint16_t {name}_data[{len(pixels)}] = {{']
    for i in range(0, len(pixels), 12):
        row = pixels[i:i+12]
        lines.append('\t' + ', '.join(f'0x{v:04x}' for v in row) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    header = f"""/*
 * icon_seed_data_64.c
 *
 * Hand-authored (SVG) icon set, rendered and packed as RGB565, {SIZE}x{SIZE}.
 * Generated by doc/icons/improved_icons/scripts/png2rgb565.py -- see svg/ for
 * the vector sources and png/ for reference renders. Same {{width, height,
 * pixels}} layout as sw/bat_source/Core/Src/icon_seed_data.c (which is
 * 48x48) -- this is a drop-in-shaped alternative at 64x64, not yet wired
 * into the firmware build (ICON_STORE_ICON_WIDTH/HEIGHT there is still 48).
 */

#include "icon_seed_data_64.h"

"""

    arrays = []
    struct_entries = []
    for name in ORDER:
        im = Image.open(os.path.join(PNG_DIR, f'{name}_64.png')).convert('RGB')
        assert im.size == (SIZE, SIZE), im.size
        pixels = [rgb565(*im.getpixel((x, y))) for y in range(SIZE) for x in range(SIZE)]
        arrays.append(emit_array(f'icon_{name}', pixels))
        struct_entries.append(f'\t{{ {SIZE}, {SIZE}, icon_{name}_data }},')

    c_src = header + '\n\n'.join(arrays) + '\n\n'
    c_src += 'const icon_seed_t icon_seeds_64[ICON_STORE_ICON_COUNT_64] = {\n'
    c_src += '\n'.join(struct_entries) + '\n};\n'

    with open(os.path.join(ROOT, 'icon_seed_data_64.c'), 'w') as f:
        f.write(c_src)

    h_src = f"""/*
 * icon_seed_data_64.h
 *
 * See icon_seed_data_64.c. Standalone reference header (does not depend on
 * the firmware's icon_store.h) so this can be reviewed/tested outside the
 * sw/bat_source build; adapt when/if wiring into the firmware.
 */

#ifndef ICON_SEED_DATA_64_H_
#define ICON_SEED_DATA_64_H_

#include "stdint.h"

#define ICON_STORE_ICON_COUNT_64  {len(ORDER)}
#define ICON_STORE_ICON_WIDTH_64  {SIZE}
#define ICON_STORE_ICON_HEIGHT_64 {SIZE}

typedef struct {{
\tuint16_t width;
\tuint16_t height;
\tconst uint16_t *pixels; /* RGB565, row-major */
}} icon_seed_t;

/* Order: {', '.join(ORDER)} */
extern const icon_seed_t icon_seeds_64[ICON_STORE_ICON_COUNT_64];

#endif /* ICON_SEED_DATA_64_H_ */
"""

    with open(os.path.join(ROOT, 'icon_seed_data_64.h'), 'w') as f:
        f.write(h_src)

    print('wrote icon_seed_data_64.c/.h with', len(ORDER), 'icons at', SIZE, 'x', SIZE)

if __name__ == '__main__':
    main()
