%% Cleanup workspace
clc;
clear;
%close all;
pkg load signal

%% Script control
PLOTTING = true;
DOWNSAMPLING_OPTIMISATION = true;
OPTIPLOTTING = true;
CODE_GENERATION = true;
tic;

%% Setup
% Temperature
temp_min_c = -50;
temp_max_c = 200;
temp_0_c = 0;
temp_0_k = 273.15;

% ADC
adc_resolution = 12;
v_ref = 2.5;

% Measurement circuit
R_Pullup = 10e3;
R_ntc_ref_c = 10e3;
B_ntc = 3380;
temp_ntc_ref_c = 25;

% Plotting
LW = 1.5;

% Data preparation
DS_FACTOR = 128;
%DS_FACTOR = 32; % Change downsampling ratio to 32 for less than 2K linearisation error
%DS_FACTOR = 256;
OPTI_DEVIATION_EXPONENT = 2;
OPTILOOPS = 300;
OPTIPLOTTING_INTERVAL = 10;

% Code generation
CODE_PATH_BASE     = '../../sw/bat_source/Core/';
CODE_PATH_SOURCE   = 'Src/';
CODE_PATH_HEADER   = 'Inc/';
CODE_FILENAME      = 'temp_conv';
CODE_SUFFIX_SOURCE = '.c';
CODE_SUFFIX_HEADER = '.h';
CODE_COMMENT_LINE  = '/*******************************************************************************/\n';
CODE_COMMENT_START = '/**\n';
CODE_COMMENT_END   = ' */\n';
CODE_AUTHOR        = ' * Author: Daniel Winz (generated)\n';
CODE_DESCRIPTION   = [' * This file contains the conversion of raw ADC values to temperature and \n' ...
                      ' * is generated by the script hw/sim/temp_ntc.m\n' ...
                      ' *\n' ...
                      ' * Parameters: \n' ...
                      ' *   NTC value at ' num2str(temp_ntc_ref_c) '°C:   ' num2str(R_ntc_ref_c/1e3) ' kOhm\n' ...
                      ' *   NTC B value:         '                          num2str(B_ntc)           ' K\n' ...
                      ' *   Pull-up resistor:    '                          num2str(R_Pullup/1e3)    ' kOhm\n' ...
                      ' *   ADC resolution:      '                          num2str(adc_resolution)  ' Bit\n' ...
                      ' *   Reference voltage:   '                          num2str(v_ref)           ' V\n' ...
                      ' *   Minimum temperature: '                          num2str(temp_min_c)      ' °C\n' ...
                      ' *   Maximum temperature: '                          num2str(temp_max_c)      ' °C\n' ...
                      ' *   Downsampling ratio:  '                          num2str(DS_FACTOR)       ' \n' ...
                     ];

%% Calculation
adc_range = 0:2.^adc_resolution-1;

adc_v_range = adc_range .* v_ref ./ (2.^adc_resolution-1);

temp_ntc_ref_k = temp_ntc_ref_c + temp_0_k;

R_ntc = R_Pullup ./ (v_ref ./ adc_v_range - 1);
R_ntc(R_ntc==0) = 1;
temp_range_k = 1 ./ ((1 ./ temp_ntc_ref_k) + (log(R_ntc ./ R_ntc_ref_c) ./ B_ntc));
temp_range_c = min(temp_max_c, max(temp_min_c, temp_range_k - temp_0_k));

%% Data preparation
adc_range_code = downsample(adc_range, DS_FACTOR);
if (adc_range_code(end) < adc_range(end))
    adc_range_code = [adc_range_code, adc_range(end)];
end;
temp_range_code = temp_range_c(adc_range_code+1);

%% Downsampling optimisation
if DOWNSAMPLING_OPTIMISATION == true
    temp_std_log = [];
    adc_range_code_initial =  adc_range_code;
    temp_range_code_initial = temp_range_code;
    temp_std_initial = std((temp_range_c - interp1(adc_range_code, temp_range_code, adc_range)).^OPTI_DEVIATION_EXPONENT);
    temp_std_opt = temp_std_initial;
    optimizing = true;
    opticounter = 1;

    if OPTIPLOTTING == true
        figure(100);
        plot(temp_range_c, temp_range_c - interp1(adc_range_code, temp_range_code, adc_range), 'Linewidth', LW);
        grid on;
        grid minor on;
        title(['NTC temperature measurement, optimization run ' num2str(opticounter) ', std: ' num2str(temp_std_opt)]);
        xlabel('ADC count [1]');
        ylabel('Temperature [\degC]');
        disp(['Prior to optimization,  Deviation: ' num2str(temp_std_initial)]);
        temp_std_log = [temp_std_initial];
    end;

    while (optimizing)
        %for (index_opt = randperm(numel(adc_range_code)-2)+1)
        for (index_opt = [2:numel(adc_range_code)-1])
            adc_opt_range = [(adc_range_code(index_opt-1)+1):(adc_range_code(index_opt+1)-1)];
            temp_std_arr = [];
            for (adc_opt = adc_opt_range)
                adc_range_code(index_opt) = adc_opt;
                temp_range_code = temp_range_c(adc_range_code+1);
                temp_std_arr = [temp_std_arr, std((temp_range_c - interp1(adc_range_code, temp_range_code, adc_range)).^OPTI_DEVIATION_EXPONENT)];
            end;
            [opt_std, opt_index] = min(temp_std_arr);
            adc_range_code(index_opt) = adc_opt_range(opt_index);
        end;
        temp_std_opt = std((temp_range_c - interp1(adc_range_code, temp_range_code, adc_range)).^OPTI_DEVIATION_EXPONENT);
        temp_std_log = [temp_std_log, temp_std_opt];
        disp(['Optimization run ' num2str(opticounter) '      Deviation: ' num2str(temp_std_opt)]);

        if (OPTIPLOTTING == true && mod(opticounter, OPTIPLOTTING_INTERVAL) == 0)
            figure(100+opticounter);
            plot(temp_range_c, temp_range_c - interp1(adc_range_code, temp_range_code, adc_range), 'Linewidth', LW);
            grid on;
            grid minor on;
            ylim([-10, 10]);
            title(['NTC temperature measurement, optimization run ' num2str(opticounter) ', std: ' num2str(temp_std_opt)]);
            xlabel('Temperature [\degC]');
            ylabel('Linearisation error [\degC]');
        end;

        if (opticounter > 5 && temp_std_log(end) == temp_std_log(end-1) && temp_std_log(end) == temp_std_log(end-2) && temp_std_log(end) == temp_std_log(end-3))
            optimizing = false;
        end;
        opticounter += 1;
        if (opticounter > OPTILOOPS)
            optimizing = false;
        end;
    end;
end;

%% Plotting
if (PLOTTING)
    figure(1);
    if DOWNSAMPLING_OPTIMISATION == true
        plot(adc_range, temp_range_c, 'g', 'Linewidth', LW, adc_range_code_initial, temp_range_code_initial, 'bx', 'Linewidth', LW, adc_range_code, temp_range_code, 'ro', 'Linewidth', LW, adc_range, interp1(adc_range_code_initial, temp_range_code_initial, adc_range), 'b--', 'Linewidth', LW/2, adc_range, interp1(adc_range_code, temp_range_code, adc_range), 'r--', 'Linewidth', LW/2);
        legend('NTC temperature', 'Linearisation with constant stepsize', 'Linearisation with optimized stepsize');
    else
        plot(adc_range, temp_range_c, 'g', 'Linewidth', LW, adc_range_code, temp_range_code, 'ro', 'Linewidth', LW, adc_range, interp1(adc_range_code, temp_range_code, adc_range), 'r--', 'Linewidth', LW/2);
        legend('NTC temperature', 'Linearisation');
    end;
    grid on;
    grid minor on;
    title('NTC temperature measurement');
    xlabel('ADC count [1]');
    ylabel('Temperature [\degC]');

    figure(2);
    plot(temp_range_c, temp_range_c - interp1(adc_range_code, temp_range_code, adc_range), 'Linewidth', LW);
    grid on;
    grid minor on;
    title('NTC temperature measurement');
    xlabel('Temperature [\degC]');
    ylabel('Linearisation error [\degC]');

    if DOWNSAMPLING_OPTIMISATION == true
        figure(3);
        plot(1:numel(temp_std_log), temp_std_log, 'Linewidth', LW);
        grid on;
        grid minor on;
        title('Optimisation progress');
        xlabel('Optimisation iteration [1]');
        ylabel('Deviation [1]');
    end;
end;

%% Code generation
if (CODE_GENERATION)
    f_source = fopen([CODE_PATH_BASE CODE_PATH_SOURCE CODE_FILENAME CODE_SUFFIX_SOURCE], 'w');
    disp(['Generating source: ' CODE_PATH_BASE CODE_PATH_SOURCE CODE_FILENAME CODE_SUFFIX_SOURCE]);
    f_header = fopen([CODE_PATH_BASE CODE_PATH_HEADER CODE_FILENAME CODE_SUFFIX_HEADER], 'w');
    disp(['Generating header: ' CODE_PATH_BASE CODE_PATH_HEADER CODE_FILENAME CODE_SUFFIX_HEADER]);

    fprintf(f_source, CODE_COMMENT_LINE);
    fprintf(f_source, CODE_COMMENT_START);
    fprintf(f_source, [' * File: ' CODE_FILENAME CODE_SUFFIX_SOURCE '\n']);
    fprintf(f_source, CODE_AUTHOR);
    fprintf(f_source, CODE_COMMENT_END);
    fprintf(f_source, CODE_COMMENT_LINE);
    fprintf(f_source, CODE_COMMENT_START);
    fprintf(f_source, CODE_DESCRIPTION);
    fprintf(f_source, CODE_COMMENT_END);
    fprintf(f_source, CODE_COMMENT_LINE);
    fprintf(f_source, ['#include <' CODE_FILENAME CODE_SUFFIX_HEADER '>\n']);
    fprintf(f_source, ['\n']);
    fprintf(f_source, ['#define TEMP_NTC_INDEX ' num2str(floor(numel(adc_range_code)/2)) '\n']);
    fprintf(f_source, ['#define TEMP_NTC_STEP  ' num2str(floor(numel(adc_range_code)/4)) '\n']);
    fprintf(f_source, ['\n']);
    fprintf(f_source, ['const uint16_t lookup_adc[' num2str(numel(adc_range_code)) '] = \n']);
    fprintf(f_source, ['{\n']);
    for (adc_code = adc_range_code(1:end-1))
        fprintf(f_source, ['     ' num2str(adc_code) ',\n']);
    end;
    fprintf(f_source, ['     ' num2str(adc_range_code(end)) '\n']);
    fprintf(f_source, ['};\n']);
    fprintf(f_source, ['\n']);
    fprintf(f_source, ['const float lookup_temp[' num2str(numel(temp_range_code)) '] = \n']);
    fprintf(f_source, ['{\n']);
    for (temp_code = temp_range_code(1:end-1))
        fprintf(f_source, ['     ' num2str(temp_code) ',\n']);
    end;
    fprintf(f_source, ['     ' num2str(temp_range_code(end)) '\n']);
    fprintf(f_source, ['};\n']);
    for code_output_type = {'int', 'float'}
        fprintf(f_source, ['\n']);
        fprintf(f_source, ['/**\n']);
        fprintf(f_source, [' * Convert the ADC value to temperature\n']);
        fprintf(f_source, [' *\n']);
        fprintf(f_source, [' * @param value ADC Value\n']);
        fprintf(f_source, [' *\n']);
        fprintf(f_source, [' * @return Temperature in Degrees (' cell2mat(code_output_type) ')\n']);
        fprintf(f_source, [' *\n']);
        fprintf(f_source, [' */\n']);
        if strcmp(cell2mat(code_output_type), 'int')
            fprintf(f_source, ['int16_t temp_deg_' cell2mat(code_output_type) '(uint16_t value)\n']);
        elseif strcmp(cell2mat(code_output_type), 'float')
            fprintf(f_source, ['float temp_deg_' cell2mat(code_output_type) '(uint16_t value)\n']);
        else
            error(['temp_ntc.m: unrecognized code output type: ' cell2mat(code_output_type)]);
        end;
        fprintf(f_source, ['{\n']);
        fprintf(f_source, ['    float temperature;\n']);
        fprintf(f_source, ['    if (value <= lookup_adc[0])\n']);
        fprintf(f_source, ['    {\n']);
        fprintf(f_source, ['        temperature = lookup_temp[0];\n']);
        fprintf(f_source, ['    }\n']);
        fprintf(f_source, ['    else if (value >= lookup_adc[' num2str(numel(adc_range_code)-1) '])\n']);
        fprintf(f_source, ['    {\n']);
        fprintf(f_source, ['        temperature = lookup_temp[' num2str(numel(adc_range_code)-1) '];\n']);
        fprintf(f_source, ['    }\n']);
        fprintf(f_source, ['    else\n']);
        fprintf(f_source, ['    {\n']);
        fprintf(f_source, ['        uint16_t index = TEMP_NTC_INDEX;\n']);
        fprintf(f_source, ['        uint16_t step = TEMP_NTC_STEP;\n']);
        fprintf(f_source, ['        while (value < lookup_adc[index] || value >= lookup_adc[index+1])\n']);
        fprintf(f_source, ['        {\n']);
        fprintf(f_source, ['            if (value < lookup_adc[index])\n']);
        fprintf(f_source, ['            {\n']);
        fprintf(f_source, ['                index -= step;\n']);
        fprintf(f_source, ['                step = (step + 1) / 2;\n']);
        fprintf(f_source, ['            }\n']);
        fprintf(f_source, ['            else if (value >= lookup_adc[index+1])\n']);
        fprintf(f_source, ['            {\n']);
        fprintf(f_source, ['                index += step;\n']);
        fprintf(f_source, ['                step = (step + 1) / 2;\n']);
        fprintf(f_source, ['            }\n']);
        fprintf(f_source, ['        }\n']);
        fprintf(f_source, ['        temperature = lookup_temp[index] + ((value-lookup_adc[index]) * (lookup_temp[index+1]-lookup_temp[index]) / (lookup_adc[index+1]-lookup_adc[index]));\n']);
        fprintf(f_source, ['    }\n']);
        if strcmp(cell2mat(code_output_type), 'int')
            fprintf(f_source, ['    return (int16_t) round(temperature);\n']);
        elseif strcmp(cell2mat(code_output_type), 'float')
            fprintf(f_source, ['    return temperature;\n']);
        else
            error(['temp_ntc.m: unrecognized code output type: ' cell2mat(code_output_type)]);
        end;
        fprintf(f_source, ['};\n']);
    end;

    fprintf(f_header, CODE_COMMENT_LINE);
    fprintf(f_header, CODE_COMMENT_START);
    fprintf(f_header, [' * File: ' CODE_FILENAME CODE_SUFFIX_HEADER '\n']);
    fprintf(f_header, CODE_AUTHOR);
    fprintf(f_header, CODE_COMMENT_END);
    fprintf(f_header, CODE_COMMENT_LINE);
    fprintf(f_header, CODE_COMMENT_START);
    fprintf(f_header, CODE_DESCRIPTION);
    fprintf(f_header, CODE_COMMENT_END);
    fprintf(f_header, CODE_COMMENT_LINE);
    fprintf(f_header, ['#ifndef ' upper(CODE_FILENAME) '_H\n']);
    fprintf(f_header, ['#define ' upper(CODE_FILENAME) '_H\n']);
    fprintf(f_header, ['#include <stdint.h>\n']);
    %fprintf(f_header, ['#include "main.h"\n']);
    fprintf(f_header, ['\n']);
    for code_output_type = {'int', 'float'}
        if strcmp(cell2mat(code_output_type), 'int')
            fprintf(f_header, ['int16_t temp_deg_int(uint16_t);\n']);
        elseif strcmp(cell2mat(code_output_type), 'float')
            fprintf(f_header, ['float temp_deg_float(uint16_t);\n']);
        else
            error(['temp_ntc.m: unrecognized code output type: ' cell2mat(code_output_type)]);
        end;
    end;
    fprintf(f_header, ['\n']);
    fprintf(f_header, ['#endif\n']);

    fclose(f_source);
    fclose(f_header);
end;
toc
