/*
 * ctrl_param.h
 *
 *  Created on: Jul 30, 2025
 *      Author: ahorat
 */

#ifndef INC_CTRL_PARAM_H_
#define INC_CTRL_PARAM_H_

#define CTRL_FREQ 20000.0F

#define CTRL_PARAM_VOLTAGE_P 0.102F
#define CTRL_PARAM_VOLTAGE_I (110.0F/CTRL_FREQ)

#define CTRL_PARAM_VOTLAGE_CURRENT_SAT_HIGH 7.0F
#define CTRL_PARAM_VOTLAGE_CURRENT_SAT_LOW 0.0F

#define CTRL_PARAM_CURRENT_P 0.377F/12.0F
#define CTRL_PARAM_CURRENT_I (3140.0F/12.0F/CTRL_FREQ)
#define CTRL_PARAM_CURRENT_DUTY_SAT_HIGH 0.9F
#define CTRL_PARAM_CURRENT_DUTY_SAT_LOW 0.0F

#define CTRL_PARAM_IDLE_VOLTAGE_1A_mV 5000
#define CTRL_PARAM_IDLE_VOLTAGE_1mA_mV 3000

#define CTRL_PARAM_CHARGE_CURRENT_mA 1000
#define CTRL_PARAM_CHARGE_END_VOLTAGE_mV (3650*4)
#define CTRL_PARAM_CHARGE_BO_VOLTAGE_mV (16000)


#endif /* INC_CTRL_PARAM_H_ */
