/*
 * ctrl_param.h
 *
 *  Created on: Jul 30, 2025
 *      Author: ahorat
 */

#ifndef INC_CTRL_PARAM_H_
#define INC_CTRL_PARAM_H_

#define CTRL_FREQ 50000.0F

#define CTRL_PARAM_SW_FREQ_HIGH 1000000
#define CTRL_PARAM_SW_FREQ_LOW  50000
#define CTRL_PARAM_CONST_DUTY_HIGH 0.985
#define CTRL_PARAM_CONST_DUTY_LOW 0.015

#define CTRL_PARAM_VOLTAGE_BOOST_P 0.01F
#define CTRL_PARAM_VOLTAGE_BOOST_I (1.0F/CTRL_FREQ)

#define CTRL_PARAM_VOLTAGE_BUCK_P 0.01F
#define CTRL_PARAM_VOLTAGE_BUCK_I (1.0F/CTRL_FREQ)

#define CTRL_PARAM_VOLTAGE_BUCK_DUTY_SAT_HIGH 0.8F
#define CTRL_PARAM_VOLTAGE_BUCK_DUTY_SAT_LOW 0.0F

#define CTRL_PARAM_VOLTAGE_BOOST_DUTY_SAT_HIGH 0.8F
#define CTRL_PARAM_VOLTAGE_BOOST_DUTY_SAT_LOW 0.015F

#define CTRL_PARAM_CURRENT_P 0.001F
#define CTRL_PARAM_CURRENT_I (0.1F/CTRL_FREQ)
#define CTRL_PARAM_CURRENT_DUTY_SAT_HIGH 0.5F
#define CTRL_PARAM_CURRENT_DUTY_SAT_LOW 0.0F

#define CTRL_PARAM_IDLE_VOLTAGE_1A_mV 5000
#define CTRL_PARAM_IDLE_VOLTAGE_1mA_mV 3000

#define CTRL_PARAM_CHARGE_CURRENT_mA 1000
#define CTRL_PARAM_CHARGE_END_VOLTAGE_mV (3650*4)
#define CTRL_PARAM_CHARGE_BO_VOLTAGE_mV (16000)


#endif /* INC_CTRL_PARAM_H_ */
