/*******************************************************************************/
/**
 * File: temp_conv.h
 * Author: Daniel Winz (generated)
 */
/*******************************************************************************/
/**
 * This file contains the conversion of raw ADC values to temperature and 
 * is generated by the script hw/sim/temp_ntc.m
 *
 * Parameters: 
 *   NTC value at 25°C:   10 kOhm
 *   NTC B value:         3380 K
 *   Pull-up resistor:    10 kOhm
 *   ADC resolution:      12 Bit
 *   Reference voltage:   2.5 V
 *   Minimum temperature: -50 °C
 *   Maximum temperature: 200 °C
 *   Downsampling ratio:  128 
 */
/*******************************************************************************/
#ifndef TEMP_CONV_H
#define TEMP_CONV_H
#include <stdint.h>

int16_t temp_deg_int(uint16_t);
float temp_deg_float(uint16_t);

#endif
