/*******************************************************************************/
/**
 * File: temp_conv.c
 * Author: Daniel Winz (generated)
 */
/*******************************************************************************/
/**
 * This file contains the conversion of raw ADC values to temperature and 
 * is generated by the script hw/sim/temp_ntc.m
 *
 * Parameters: 
 *   NTC value at 25°C:   10 kOhm
 *   NTC B value:         3380 K
 *   Pull-up resistor:    10 kOhm
 *   ADC resolution:      12 Bit
 *   Reference voltage:   2.5 V
 *   Minimum temperature: -50 °C
 *   Maximum temperature: 200 °C
 *   Downsampling ratio:  128 
 */
/*******************************************************************************/
#include <temp_conv.h>
#include "math.h"

#define TEMP_NTC_INDEX 16
#define TEMP_NTC_STEP  8

const uint16_t lookup_adc[33] = 
{
     0,
     61,
     69,
     70,
     71,
     72,
     73,
     74,
     75,
     76,
     77,
     91,
     109,
     131,
     158,
     192,
     234,
     287,
     352,
     434,
     537,
     667,
     833,
     1046,
     1325,
     1706,
     3065,
     3425,
     3661,
     3819,
     3924,
     4011,
     4095
};

const float lookup_temp[33] = 
{
     200,
     199.9123,
     191.7645,
     190.8304,
     189.9129,
     189.0116,
     188.126,
     187.2555,
     186.3997,
     185.5581,
     184.7303,
     174.3907,
     163.6904,
     153.2535,
     143.0551,
     132.877,
     122.9492,
     113.0828,
     103.5539,
     94.0765,
     84.6878,
     75.3168,
     65.8156,
     56.0686,
     45.7438,
     34.1269,
     -1.163,
     -12.5115,
     -22.2038,
     -31.0976,
     -39.5597,
     -50,
     -50
};

/**
 * Convert the ADC value to temperature
 *
 * @param value ADC Value
 *
 * @return Temperature in Degrees (int)
 *
 */
int16_t temp_deg_int(uint16_t value)
{
    float temperature;
    if (value <= lookup_adc[0])
    {
        temperature = lookup_temp[0];
    }
    else if (value >= lookup_adc[32])
    {
        temperature = lookup_temp[32];
    }
    else
    {
        uint16_t index = TEMP_NTC_INDEX;
        uint16_t step = TEMP_NTC_STEP;
        while (value < lookup_adc[index] || value >= lookup_adc[index+1])
        {
            if (value < lookup_adc[index])
            {
                index -= step;
                step = (step + 1) / 2;
            }
            else if (value >= lookup_adc[index+1])
            {
                index += step;
                step = (step + 1) / 2;
            }
        }
        temperature = lookup_temp[index] + ((value-lookup_adc[index]) * (lookup_temp[index+1]-lookup_temp[index]) / (lookup_adc[index+1]-lookup_adc[index]));
    }
    return (int16_t) round(temperature);
};

/**
 * Convert the ADC value to temperature
 *
 * @param value ADC Value
 *
 * @return Temperature in Degrees (float)
 *
 */
float temp_deg_float(uint16_t value)
{
    float temperature;
    if (value <= lookup_adc[0])
    {
        temperature = lookup_temp[0];
    }
    else if (value >= lookup_adc[32])
    {
        temperature = lookup_temp[32];
    }
    else
    {
        uint16_t index = TEMP_NTC_INDEX;
        uint16_t step = TEMP_NTC_STEP;
        while (value < lookup_adc[index] || value >= lookup_adc[index+1])
        {
            if (value < lookup_adc[index])
            {
                index -= step;
                step = (step + 1) / 2;
            }
            else if (value >= lookup_adc[index+1])
            {
                index += step;
                step = (step + 1) / 2;
            }
        }
        temperature = lookup_temp[index] + ((value-lookup_adc[index]) * (lookup_temp[index+1]-lookup_temp[index]) / (lookup_adc[index+1]-lookup_adc[index]));
    }
    return temperature;
};
